#!/bin/bash

ROMDIR=/tmp/rom
MANIFEST=https://github.com/DotOS/manifest
BRANCH=dot11


mkdir -p "$ROMDIR"
cd "$ROMDIR"

# Repo init command
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name Rodeobazaar124
git config --global user.email azfasa15@gmail.com

git clone https://github.com/nrudesu/local_manifests --depth 1 -b certus-r .repo/local_manifests

# Sync source with -q
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# bringup droid on time os
cd $ROMDIR/device/xiaomi/certus
mv komodo_certus.mk dot_certus.mk
mv komodo.dependencies dot.dependencies
sed -i "s/komodo/dot/" AndroidProducts.mk dot_certus.mk
sed -i "s/_full_phone//" dot_certus.mk

# Disable serial console notification
cd $ROMDIR/device/xiaomi/certus/rootdir/etc
rm -rf init.target.rc
wget -c https://del.dog/raw/certus-rootdir-init-svc
mv certus-rootdir-init-svc init.target.rc

# Replace LatinIME to modified LatinIME for better interface :p
rm -rf "$ROMDIR"/packages/inputmethods/LatinIME
git clone https://github.com/AOSiP/platform_packages_inputmethods_LatinIME -b eleven "$ROMDIR"/packages/inputmethods/LatinIME

# Codec Patch
cd "$ROMDIR"/frameworks/av
wget https://github.com/SamarV-121/android_vendor_extra/raw/lineage-18.1/patches/frameworks/av/0005-Don-t-fail-AAC-decoding-if-DRC-parameter-isn-t-avail.patch
git am 0005-Don-t-fail-AAC-decoding-if-DRC-parameter-isn-t-avail.patch
git add .
git am --continue
cd "$ROMDIR"

# Fix Hotspot in R
cd "$ROMDIR"/system/netd
wget https://github.com/phhusson/platform_system_netd/commit/0296b55efeaae8cc835a6e2645531b29e10fb934.patch
git am 0296b55efeaae8cc835a6e2645531b29e10fb934.patch
git add .
git am --continue
cd "$ROMDIR"
