#!/bin/bash

ccache -s

cd /tmp

date=`date +%Y%m%d`

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache-potato-certus # Compression level 1, its enough

up(){
	curl --upload-file $1 https://bashupload.com/$(basename $1)
}

up ccache-potato-certus.tar.gz
